# This file is a template, and might need editing before it works on your project.
react-build-tags:
  # Official docker image.
  image: docker:latest
  stage: build
  variables:
    DOCKER_TAG: $(echo "$CI_COMMIT_TAG" | cut -d '-' -f2-)
    REGISTY_IMAGE: $DOCKER_SERVER/$IMAGE_REPOSITORY:$DOCKER_TAG
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD hub.mfec.co.th
  script:
    - echo "[1/3] Start building image $REGISTY_IMAGE"
    - docker build --build-arg SERVER_ENV=$server_env --build-arg VERSION=$CI_COMMIT_TAG -t $REGISTY_IMAGE .
    - echo "[2/3] Pushing image $REGISTY_IMAGE to $DOCKER_SERVER"
    - docker push $REGISTY_IMAGE
    - echo "[3/3] Finished build image"

    # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    # - docker push "$CI_REGISTRY_IMAGE"
  after_script:
    - docker logout $DOCKER_SERVER
  only:
    - tags
